
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/springboot_test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
