spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/springboot_test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  type-aliases-package: com.my.springboot.bean
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl